# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Arbor::Server"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

#template: "template_toolkit"
engines:
    template_toolkit:
        COMPILE_DIR: "/tmp/arbor-templates"
        COMPILE_EXT: ".ttc"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

# database: "arbor.db"
# configurable to use multiple connections
# http://advent.perldancer.org/2010/11
# uses DBIx::Class backend

plugins:
  DBIC:
    arbor:
        schema_class: Arbor::Schema
        dsn: "dbi:SQLite:dbname=arbor.db"  

# session management done through dancer
# using YAML backend for easier debugging

session: "YAML"
session_dir: "/tmp/arbor-sessions"
